### ISSUE TITLE
Lock actuator motor plate STL not updated for LDO diameter

### ISSUE THREAD

**Issue by coldelectrons** [machineagency/jubilee#104]
Somehow, the STL was 'updated' at the same time as the motor base, but the diameter still corresponds to the StepperOnline motor. The corresponding part in the jubilee.STEP file is correct, however.

This is in the latest commit, 76700425b644e68d5f71041afc3d75ebb93b6ec9

**Comment by Poofjunior** [comment]
Really good catch! Thanks for bringing this up! This should be fixed in this commit
https://github.com/machineagency/jubilee/commit/c35194454748a60f64e4b1f1ce74d91bc4b35f9a?short_path=d27935d

(Checked against Github's nice STL diff rendering feature)
