### ISSUE TITLE
Images missing from Bondtech groovemount extruder assembly instructions. 

### ISSUE THREAD

**Issue by SteveJWallace** [machineagency/jubilee#107]
On sheet 8 of 14 on the [Bondtech groove mount extruder assembly instructions](https://github.com/machineagency/jubilee/blob/master/tools/jubilee_tools/tools/extruders/direct_drive_bondtech_groovemount_extruder/assembly_instructions/bondtech_groovemount_extruder_assembly_instructions.pdf) several images appear to be missing.

**Comment by Poofjunior** [comment]
Ok; these are now fixed!
