### ISSUE TITLE
Side Panel Modification for improved manufacturability

### ISSUE THREAD

**Issue by elmoret** [machineagency/jubilee#109]
When cutting material on a CNC, the material must be held down either through clamps, or through screws in holes in the material. The side panels are approximately 19"x24", which allows them to fit 10 to a standard sheet. However, doing this offers very little extra material for clamping the edges while cutting, so it would be beneficial to add holes for hold-down purposes. Please see attached proposed positions, they can be the same size as other holes on the panels.
![image (12)](https://user-images.githubusercontent.com/3068738/87884065-a6198d00-c9d9-11ea-8026-9463dc24453a.png)
![image (11)](https://user-images.githubusercontent.com/3068738/87884066-a6b22380-c9d9-11ea-90d2-4a92abb260e9.png)

**Comment by Poofjunior** [comment]
Holes are added and uploaded! Thanks for the heads-up, and glad it's saving material.
https://github.com/machineagency/jubilee/tree/master/frame/fabrication_exports/machined_parts/panels
