### ISSUE TITLE
Misconfigured System Breaks X Axis Limit Switch

### ISSUE THREAD

**Issue by Poofjunior** [machineagency/jubilee#112]
If the machine is not responding to endstops, the machine can damage the X limit switch while homing as it continues to travel into the switch, crushing it.

It would make sense to create a situation where, even if the switch doesn't trigger, the machine hard-stops, rather than causing damage to itself that requires the user to service it. (The Y Axis is like this. Rather than break the switch, it hard-stops into the frame.)

**Comment by coldelectrons** [comment]
I suggest a modification of CBP-05: extend the plastic past the switch by 3.0 to 3.2 mm. Based on my digital calipers and one of those switches, that is how far the plunger still extends when triggered. The switch itself can remain in the exact same position.
I myself have now clobbered two of those switches getting my Jubilee moving for the first time.

**Comment by Poofjunior** [comment]
Thanks for the rec @coldelectrons ! This is one possible solution. We'll have to check to see if we need to modify the corresponding tab where the switch triggers, so there's a low-stress surface to act as a hard-stop.

**Comment by Poofjunior** [comment]
Ok, here is an in-progress solution in related issue: https://github.com/machineagency/jubilee/issues/180

**Comment by Poofjunior** [comment]
Ok, instructions are updated.
This part is now in the print list:
https://github.com/machineagency/jubilee/blob/main/frame/fabrication_exports/3d_printed_parts/frame/x_axis_hard_stop.STL

And I think we're a lot better now than where we were!
