### ISSUE TITLE
M5x10x0.2mm shims from McMaster might not fit on spindle.

### ISSUE THREAD

**Issue by JacobRoth** [machineagency/jubilee#118]
M5x10x0.2 shims from McMaster-Carr (part number 98089A246) have an ID tolerance that allows them to be as small as 4.7mm, which can make them too tight to fit on the twist lock spindle. In my case none of an entire 25 pack of these shims could fit onto my spindle.

**Comment by Poofjunior** [comment]
Ok, these are removed from the BOM as alternates to the Aliexpress ones. Thanks a bunch for the heads-up.
