### ISSUE TITLE
Toolchanger Remote Elastic Lock Assembly references outdated version of part

### ISSUE THREAD

**Issue by ioben** [machineagency/jubilee#134]
The assembly instruction PDF for the [Toolchanger Remote Elastic Lock Assembly](https://github.com/machineagency/jubilee/blob/master/frame/assembly_instructions/toolchanger_mechanism/toolchanger_lock_assembly_instructions.pdf) currently references part CPL-01 on pages 15-17. The next set of instructions in [Toolchanger Carriage Assembly](https://github.com/machineagency/jubilee/blob/master/frame/assembly_instructions/toolchanger_mechanism/toolchanger_carriage_assembly_instructions_draft.pdf) references CPL-02. This disparity initially led me to believe they were two different parts.

Simple fix, but I think it'd help clarity between these two steps quite a bit.

**Comment by Poofjunior** [comment]
Aye; that's definitely an issue. I'll have that fixed up for the next release. Thanks for writing this in!
