### ISSUE TITLE
Possible security breach on Jubilee wiki site

### ISSUE THREAD

**Issue by mhipszki** [machineagency/jubilee#139]
There seem to be unwanted changes on the Jubilee wiki looking at the change log:

![Screenshot 2020-12-14 at 10 41 20](https://user-images.githubusercontent.com/220661/102071970-1eee0b00-3df9-11eb-9fde-3ae340d8b2a8.png)

The _Main page_ content also looks weird...

This is a fantastic project and thought it'd be useful to flag that @Poofjunior  🙂

**Comment by HaythamB** [comment]
Yup looks like its been hacked. I'll see if I can disable new users for the time being until Joshua is on US daytime!

**Comment by HaythamB** [comment]
@Poofjunior I think you'll need to install https://www.mediawiki.org/wiki/Extension:UserMerge

I'm deleting all the spam pages, already restored the wiki contents page-by-page to remove all the bots' updates.

**Comment by HaythamB** [comment]
And looks like we started getting spam users as far back as December 3rd.

**Comment by HaythamB** [comment]
2549 pages deleted so far..

**Comment by mhipszki** [comment]
😱  omg

**Comment by Prexsys-Beach** [comment]
Why can’t we have nice things? :)

**Comment by Poofjunior** [comment]
Oof; thanks for bringing this up @mhipszki , and thanks for axing the spam pages @HaythamB . 
I only noticed the front page last night and promptly changed it back and blocked the user.

Yeah; it looks like we've hit a critical mass where we might have to add some flavor of captcha to keep the spam at bay longer term.

**Comment by HaythamB** [comment]
Ready to be marked as done, and I've created a relevant issue for addressing this in the longer term #141

**Comment by Poofjunior** [comment]
Thanks a bunch @HaythamB !
