### ISSUE TITLE
Better anti-spam filtering needed on Jubilee3d.com

### ISSUE THREAD

**Issue by HaythamB** [machineagency/jubilee#141]
We now have reCAPTCHA enabled on user account creation, but ideally we need a more robust and spam proof antispam module to be activated on the Wiki.

Suggestion for fix: use QuestyCaptcha module with some customized questions that allows for true human validation for user activities..

**Comment by Poofjunior** [comment]
I think we've been able to cook up a pretty good workaround.

The Mediawiki now asks for your Discord Handle when you request an account. We confirm you are indeed human by reaching out to you on Discord through our "account-requests" channel. And--voila! A manual-but-pretty-effective form of two factor authentication!

Thanks for bringing this up and helping us cook up a solution @HaythamB !
