### ISSUE TITLE
Images missing from extruder tool assembly instructions

### ISSUE THREAD

**Issue by vcapra1** [machineagency/jubilee#143]
I think something is missing from these instructions:

https://github.com/machineagency/jubilee/blob/master/tools/jubilee_tools/tools/extruders/direct_drive_bondtech_groovemount_extruder/assembly_instructions/bondtech_groovemount_extruder_assembly_instructions.pdf

![image](https://user-images.githubusercontent.com/23411890/103923532-36ac6c80-50e3-11eb-9610-1394ffc1e1dd.png)

**Comment by vcapra1** [comment]
Also, item names missing from same document:

![image](https://user-images.githubusercontent.com/23411890/103924457-074a2f80-50e4-11eb-87d7-17007405f44a.png)

**Comment by Poofjunior** [comment]
These should now be fixed!
