### ISSUE TITLE
Duet 2/RRF3 Config.g mixes up PT100/PT1000

### ISSUE THREAD

**Issue by FL-CDF** [machineagency/jubilee#145]
In the config regarding the extruder temperature sensor there is a mix up betwin PT100&PT1000

The current code also didn work with the stock E3D PT1000.
The currend code in config.g : M308 S1 P"e0_temp" Y"pt100" R4700       ; PT1000-style E0 temperature sensor

Corrected code for the BMG tool with V6: 
M308 S1 P"e0_temp" Y"thermistor" T100000 B4725 C7.06e-8     ; PT1000-style E0 temperature sensor stock E3D

**Comment by Poofjunior** [comment]
Much appreciated! I'll squeeze this into the next release.

**Comment by Poofjunior** [comment]
Ok, so apparently the R parameter is autospecified in Duet3, so we can just leave it out.
https://duet3d.dozuki.com/Wiki/Connecting_thermistors_or_PT1000_temperature_sensors#Section_The_M305_M308_R_parameter
(Oof; that threw me on a side quest.)

**Comment by Poofjunior** [comment]
Ok; this is now up-to-date. Thanks for the heads-up!
