### ISSUE TITLE
rrf3 home macro fix

### ISSUE THREAD

**Issue by grzesiekn** [machineagency/jubilee#156]
When I try to home X axes first I getting message "G28 may not be used within a homing file". Any solution for this - except: home U,Y first.
I think You can replace **G28** with **M98 P"home?.g"**
Affected files homex.g and homez.g

It will be good idea to add an IF before Rapid moves in tfree, tpost, tpre files
if move.axes[1].userPosition >= 305
  G0 Y305 F20000             ; Rapid to safe y position

It looks like in the file confg.g M950 commands is missing that defines heater fans:
M950 F1 C"fan1"                         ; Fan 1, heater cooler fan on Tool 0
M950 F3 C"fan3"                         ; Fan 2, heater cooler fan on Tool 1

**Comment by Poofjunior** [comment]
Ok; I think this actually got fixed on Feb 11.
https://github.com/machineagency/jubilee/commit/dc2cee648ddfca3b81d67750f0e6f9638a68ccb1

If there's still an issue, fee free to comment in the thread. But I'll close it for now.
