### ISSUE TITLE
Frame assembly instructions pdf - call out set screws in corner brackets

### ISSUE THREAD

**Issue by kelliead** [machineagency/jubilee#158]
On the frame assembly instructions pdf, suggest including a note about preloading the M4x4mm set screws in the inside corner brackets prior to assembly. 

It's not obvious to novice builders that the set screws come separately and need to be loaded into the brackets, and a few have gotten to the tightening step and realized there's nothing there to tighten. A simple note early in the instructions would save some confusion and time. 

This would be helpful on sheet 3 of 28: 

<img width="803" alt="Screen Shot 2021-02-11 at 5 42 28 PM" src="https://user-images.githubusercontent.com/49258142/107721246-0bdca780-6c91-11eb-8308-6a7a4346be31.png">

**Comment by Poofjunior** [comment]
Ok, there is now a preloading page in the instructions that happens before this:
https://docs.google.com/viewer?url=github.com/machineagency/jubilee/raw/master/frame/assembly_instructions/frame/inside_corner_bracket_prep.pdf
