### ISSUE TITLE
parts with heat set inserts PDF - update 

### ISSUE THREAD

**Issue by kelliead** [machineagency/jubilee#159]
Parts With Heat Set Inserts instructions PDF: the CAD illustrations are out of date for some of the current parts:

Sheet 1 of 5:
CPL-02 inaccurate
CCP-04 missing

Sheet 2 of 5:
RLB-10 inaccurate
CBP-05 inaccurate

Generally, labeling all illustrations with their part numbers on the pages, or providing a written part list (in a corner legend box) of all of the part numbers to gather before starting, would be helpful!

**Comment by Poofjunior** [comment]
Ok; I think these are all checked off.

I thought about doing a table for these, but I just renamed all the parts with their part numbers instead. That way they don't have to do any mental gymnastics of hunting down a line of text on a physical part. Hopefully that makes sense?
