### ISSUE TITLE
Motor Plate Assembly instructions PDF: correct number of screws

### ISSUE THREAD

**Issue by kelliead** [machineagency/jubilee#162]
Motor Plate Assembly instructions PDF: 

Sheet 7 of 11 calls for six screws, but only four are used in the step:
<img width="805" alt="Screen Shot 2021-02-11 at 6 35 23 PM" src="https://user-images.githubusercontent.com/49258142/107724298-66c5cd00-6c98-11eb-937b-6bda013628c3.png">

The issue repeats again on sheet 11 of 11:
<img width="805" alt="Screen Shot 2021-02-11 at 6 40 05 PM" src="https://user-images.githubusercontent.com/49258142/107724467-c6bc7380-6c98-11eb-9363-9eb730c40087.png">

**Comment by Poofjunior** [comment]
Good catch! Tis now fixed.
