### ISSUE TITLE
Double Pulley Corner Plate assembly PDF - update

### ISSUE THREAD

**Issue by kelliead** [machineagency/jubilee#163]
Double Pulley Corner Plate assembly PDF has outdated illustrations/instructions about drop-in T-nuts on sheets 1, 4, and 7:

<img width="811" alt="Screen Shot 2021-02-12 at 6 54 27 PM" src="https://user-images.githubusercontent.com/49258142/107839985-1c118700-6d64-11eb-8771-14b18a7f7cb1.png">
<img width="810" alt="Screen Shot 2021-02-12 at 6 58 18 PM" src="https://user-images.githubusercontent.com/49258142/107840068-81657800-6d64-11eb-9786-84370b7f4b35.png">
<img width="808" alt="Screen Shot 2021-02-12 at 7 00 54 PM" src="https://user-images.githubusercontent.com/49258142/107840093-bbcf1500-6d64-11eb-9ebb-40886af06962.png">

It may also be helpful to note on sheets 2,3 and 5,6 that the bumps on the reinforcement plate go towards the standoffs: 

<img width="810" alt="Screen Shot 2021-02-12 at 7 04 26 PM" src="https://user-images.githubusercontent.com/49258142/107840191-85de6080-6d65-11eb-80cb-ab167836dfcf.png">

**Comment by Poofjunior** [comment]
Great point on the orientation of those bumps! This is now up to date.
