### ISSUE TITLE
Toolchanger Lock Assembly PDF - updates

### ISSUE THREAD

**Issue by kelliead** [machineagency/jubilee#164]
Toolchanger Lock Assembly PDF 

Sheet 5 still has instructions and illustrations for drop-in T-nuts: 

<img width="811" alt="Screen Shot 2021-02-12 at 7 10 00 PM" src="https://user-images.githubusercontent.com/49258142/107840282-495f3480-6d66-11eb-8a6a-1b40bcbaaa04.png">

On sheet 16, the screw on CPL-02 is assumed to have been pre-installed, but this step doesn't appear in the previous instructions. It shows up later in sheet 3 of 7 on the carriage assembly, but if the builder is following the order of subassemblies on the wiki, they haven't done that step yet. Suggest adding the M3 6mm buttonhead screw to the parts list for this page and installing it in this step:

<img width="812" alt="Screen Shot 2021-02-12 at 7 13 57 PM" src="https://user-images.githubusercontent.com/49258142/107840349-da361000-6d66-11eb-9e76-588afaf32d6b.png">

**Comment by Poofjunior** [comment]
Ok, Tnuts removed! That screw is actually mentioned in a separate set of instructions for the carriage parts, so I'll leave that second part as-is.
