### ISSUE TITLE
XY Frame Assembly instructions PDF corrections

### ISSUE THREAD

**Issue by kelliead** [machineagency/jubilee#170]
XY Frame Assembly instructions PDF:

Sheet 13 of 18, the written instructions cite different item numbers than the legend:
<img width="831" alt="Screen Shot 2021-02-19 at 6 06 41 PM" src="https://user-images.githubusercontent.com/49258142/108579840-bf6f1880-72dd-11eb-8006-669535435913.png">

Sheet 17 of 18, the legend calls for 2300mm belt lengths, which is excessively long. I trimmed mine to 2155mm to start with:
<img width="827" alt="Screen Shot 2021-02-19 at 6 11 31 PM" src="https://user-images.githubusercontent.com/49258142/108579984-54721180-72de-11eb-8bb5-0a31ede0a026.png">

**Comment by Poofjunior** [comment]
Nice! I really appreciate having an actual number on this!
