### ISSUE TITLE
RRF3 cinfig.g bed thermistor missing " Y"thermistor"

### ISSUE THREAD

**Issue by EBLux** [machineagency/jubilee#182]
Jubilee 2.2.0 Config File for RepRapFirmware 3

; Machine Thermistors
M308 S0 S"bed_temp" T100000 B3950 R4700 ; Define built-in Keenovo Bed Thermistor values.

should read

M308 S0 P"bed_temp" Y"thermistor" T100000 B3950 R4700 ; Define built-in Keenovo Bed Thermistor values

**Comment by Poofjunior** [comment]
Ah ok. It looks like this was correct in the Duet3 config files but missing in the Duet 2 config files.

It has now been fixed.

Thanks for the heads up!
