### ISSUE TITLE
Outer Frame Assembly and Instructions

### ISSUE THREAD

**Issue by cindygfeng** [machineagency/jubilee#21]
Sheet 6 of 11: We found it easier to slide the L brackets onto the shorter 409 mm TSlot Extrusions first, keeping in mind the direction of the L brackets.  Then slide all 4 onto the 604mm long extrusions.

Also circled the two middle L brackets that we forgot again.

![image](https://user-images.githubusercontent.com/49258117/73327609-844e0300-420b-11ea-994c-cefbaca2d886.png)

**Comment by Poofjunior** [comment]
I will definitely make a note of this. Thanks for the heads up.
