### ISSUE TITLE
Outer Frame Assembly and Instructions

### ISSUE THREAD

**Issue by cindygfeng** [machineagency/jubilee#22]
Generally, we'd like the upper and lower frames to be called out more consistently.  For example on sheet 8, it is called prior frame and loose frame, but at the bottom it is called upper and lower frame.

![image](https://user-images.githubusercontent.com/49258117/73327792-31c11680-420c-11ea-99bc-ffc44f1eeb78.png)

**Comment by Poofjunior** [comment]
Yeah; I think splitting this into two pages will also make it easier. Will rename as suggested. Thanks!
