### ISSUE TITLE
Lower Frame Assembly instructions - Back Z Motor Plate Assembly 2

### ISSUE THREAD

**Issue by kelliead** [machineagency/jubilee#28]
Lower Frame Assembly instructions, sheet 6 of 14, Back Z Motor Plate Assembly 2

Add note that says which direction the wires on the motor go (if it matters). 
Specify to put the dab of threadlock on the tip threads of the screws.

![IMG_5421](https://user-images.githubusercontent.com/49258142/73808620-6b060300-4785-11ea-9fb0-4d3eec639c7c.JPG)

**Comment by Poofjunior** [comment]
Wire notes and threadlock note added!
