### ISSUE TITLE
Lower Frame Assembly instructions - both Front Z Plate Assemblies

### ISSUE THREAD

**Issue by kelliead** [machineagency/jubilee#29]
Lower Frame Assembly instructions, Sheet 8 of 14, Front Left Z Plate Assembly 2
and Sheet 10 of 14, Front Right Z Plate Assembly 2

Specify where to put the dab of threadlock. 
Add note/image that wires go in direction of slot on plate.

![IMG_5422](https://user-images.githubusercontent.com/49258142/73808684-a56fa000-4785-11ea-8ff1-c7c0f51d3a58.JPG)
![IMG_5423](https://user-images.githubusercontent.com/49258142/73808742-dbad1f80-4785-11ea-8c32-bde0a0e4ec56.JPG)

**Comment by Poofjunior** [comment]
The deed is done :)
