### ISSUE TITLE
Lower Frame Assembly instructions - Internal Extrusion Alignment

### ISSUE THREAD

**Issue by kelliead** [machineagency/jubilee#30]
Lower Frame Assembly instructions, Sheet 11 of 14, Internal Extrusion Alignment

Specify to slide in the 2 inside corner brackets that are included in the diagram but not mentioned anywhere until the next page.

Point out that the corner brackets slide into the inside of the back Z plate. 

![IMG_5424](https://user-images.githubusercontent.com/49258142/73808862-2cbd1380-4786-11ea-89fa-1feffc35bdb1.JPG)

**Comment by Poofjunior** [comment]
Got this one!
