### ISSUE TITLE
Lower Frame Assembly instructions - Z Plate Tightening

### ISSUE THREAD

**Issue by kelliead** [machineagency/jubilee#31]
Lower Frame Assembly instructions, sheet 13 of 14, Z Plate Tightening

Add dimensions for correct placement of back Z plate using a ruler. 15.5cm from edge of plate to inside edge of side extrusion.

![IMG_5425](https://user-images.githubusercontent.com/49258142/73808941-67bf4700-4786-11ea-9d61-d6c2de03efb1.JPG)

**Comment by Poofjunior** [comment]
Ok, so it turns out that I did add this info--I just never exported it--doh!

**Comment by Poofjunior** [comment]
@kelliead @awaer @cindygfeng actually this is already fixed and pushed online. make sure you're working off the latest instructions on the web, not a local copy that you downloaded.

**Comment by cindygfeng** [comment]
@Poofjunior We were working off of instructions that we printed that day from the Assembly Instructions wiki page.  Perhaps the link hadn't been updated, and that's why we had old instructions? @kelliead
