### ISSUE TITLE
Left motor plate assembly: stepper is missing from parts list 

### ISSUE THREAD

**Issue by awaer** [machineagency/jubilee#32]
Left motor plate assembly instructions 3/3 (1/29/2020: sheet 7 of 11) is missing a reference to the stepper motor w/ drive pulley. 

<img width="703" alt="Screen Shot 2020-02-04 at 8 17 43 PM" src="https://user-images.githubusercontent.com/10305/73810679-0dc18000-478c-11ea-965c-26f7d987fdb3.png">

**Comment by Poofjunior** [comment]
Okk, this is now added.
