### ISSUE TITLE
Default tool size limits maximum bed size to 290 in Y

### ISSUE THREAD

**Issue by Poofjunior** [machineagency/jubilee#4]
This picture says it all. 

https://media.discordapp.net/attachments/627988602269335568/639674827103273000/IMG_0850.jpeg?width=893&height=670

Essentially, the default tool's thickness limits the print area in the y direction to about 290mm in a multitool printing setup.

**Comment by DanalEstes** [comment]
I believe this can be resolved by making the right and left rail of the upper frame longer, thus moving out the "upper front" rail that carries the tools, moving it in the Y direction.  It looks like we need about 15 to 20 more mm. Relocate the front R/L pulley assemblies by the same amount. That implies longer belts. I don't believe any other part of the printer would have to change, in a "retrofit" situation. Not even the linear slides.

**Comment by solhuebner** [comment]
@DanalEstes As this was implemented in 2.0, can this issue be closed?

**Comment by Poofjunior** [comment]
@solhuebner aye!
This is fixed as of rel/2.0
https://github.com/machineagency/jubilee/blob/master/CHANGELOG.md#reljubilee-20---jan-15-2020
