### ISSUE TITLE
Build plate assembly instructions: bed orientation is missing

### ISSUE THREAD

**Issue by awaer** [machineagency/jubilee#41]
Sheet 4 of 13 is missing an annotation to indicate bed orientation (see example), which could prevent some users from erroneously installing the M3 screws on the wrong side.

<img width="707" alt="Screen Shot 2020-02-11 at 5 44 31 PM" src="https://user-images.githubusercontent.com/10305/74295664-91342180-4cf6-11ea-99a6-cba0876c7dd7.png">

**Comment by Poofjunior** [comment]
this is now up to date!
