### ISSUE TITLE
CoreXY Frame Assembly Instructions: Toolchanger Locking Mechanism Items

### ISSUE THREAD

**Issue by BryanHaven** [machineagency/jubilee#42]
Assembling the spring guides and sheath before running wire rope through the spring guides. 
Run two 600mm spring guides through nylon sheath (1/8" was used and worked). 
Leave 25 mm of spring guide exposed on the carriage end and 55 mm of spring guide exposed on lock actuator end.
Ensure spring guides are even on each end. 
Use adhesive lined shrink tubing is used to affix sheath to spring guide. 

Spring guide anchor block not listed - very useful for managing spring guides without a third hand. 

See Jubilee Day 21 Livestream @ 1:40

**Comment by Poofjunior** [comment]
I think this new assembly procedure is now pretty well captured in the new instructions. Anchor Block is also restored.
