### ISSUE TITLE
Config files for OMC/StepperOnline 5:1 planetary motors need to be updated

### ISSUE THREAD

**Issue by HaythamB** [machineagency/jubilee#46]
Currently the steps per mm for the toolchanger locking mechanism is set to the LDO variant. The OMC variant should have a different steps per mm listed as an option for ease of configuration setup as per the BOM.

The correct steps per mm would be 11.429 for an OMC stepper, and the relevant M92 command should be reflecting this option.

**Comment by Poofjunior** [comment]
This is fixed! Thanks for the heads-up.
