### ISSUE TITLE
Add additional clearance on motor mounts.

### ISSUE THREAD

**Issue by SteveJWallace** [machineagency/jubilee#68]
Additional clearance should be implemented on the slot that allows the motors to slide along the plate. It was necessary to add 0.3mm to each one for the motors to fit in place snugly.  The parts were printed with the recommended settings in PETG. 

[Motor Corner Brackets.zip](https://github.com/machineagency/jubilee/files/4341282/Motor.Corner.Brackets.zip)

**Comment by Poofjunior** [comment]
This is now fixed in master.
