### ISSUE TITLE
BOM Error, M2 Buttonhead screw, 8mm long missing

### ISSUE THREAD

**Issue by SteveJWallace** [machineagency/jubilee#73]
The BOM is missing the M2 Buttonhead screw, 8mm long that was mentioned in the instructions for the toolchanger lock assembly on sheet 7 of 15.

**Comment by Poofjunior** [comment]
Oh, these are in the McMaster-Carr section, since they need to be buttonhead, which BoltDepot doesn't have. 

Alas, you need to buy a 100-pack for only two screws, but def will take suggestions for other places.

**Comment by Poofjunior** [comment]
spoke too soon!
https://www.aliexpress.com/item/33007621009.html

**Comment by VinnyCordeiro** [comment]
There's this link for titanium-plated screws that can be bought down to only 5 units, if you don't mind golden screws: https://www.aliexpress.com/item/4000352613356.html
