### ISSUE TITLE
Z-Axis - improved genericism across motor brands

### ISSUE THREAD

**Issue by BryanHaven** [machineagency/jubilee#76]
Many motors have varying shaft lengths - topping out at 25mm. Adding to motor plate thickness and z-thrust spacer should resolve.

**Comment by Poofjunior** [comment]
@BryanHaven just curious: in your implementation, how much space did you put between the motor and the Z plate? What's your spacer length?

**Comment by Poofjunior** [comment]
This has been bumped down in 2.1.0 such that the leadscrew need only be installed 7-to-9mm, rather than bottom out in the plastic piece.

**Comment by Poofjunior** [comment]
Oh, and motors of 24 and 25mm shafts should work in this section as well!
