### ISSUE TITLE
Where is the Top Lock Actuator Plate?

### ISSUE THREAD

**Issue by vcapra1** [machineagency/jubilee#8]
In the assembly instructions (page 2 of [toolchanger_lock_assembly_instructions.pdf](https://github.com/machineagency/jubilee/blob/master/assembly_instructions/toolchanger_mechanism/toolchanger_lock_assembly_instructions.pdf)), it says a "Top Lock Actuator Plate" is needed.  There is no such part in the list of 3d printed parts.  The closest thing I can find is the "Lock Actuator Base Plate", which is referenced on the following page and does in fact exist in the list of 3d printed parts.

The image of the Top Lock Actuator Plate does not match the 3d model, but the model does match the Lock Actuator Base Plate on the following page.  In the first case, there are 2 more holes and 2 slots in the side of the part, which don't exist on the next page, or the 3d model.  Am I to assume these are in fact the same part, and those holes/slots are not necessary?

**Comment by timcurtis67** [comment]
I believe the part you are looking for is really called "top_lock_actuator_plate_Spring Guide Anchor Block.stl" or .sldprt. Here is a copy of that file.

All of the holes are used, the extra holes you see are to bolt this part to the base plate.
[top_lock_actuator_plate_Spring Guide Anchor Block.zip](https://github.com/machineagency/jubilee/files/4005157/top_lock_actuator_plate_Spring.Guide.Anchor.Block.zip)

**Comment by vcapra1** [comment]
That is not what I meant.  The assembly instructions show the following part:
![2019-12-28_11 55 09](https://user-images.githubusercontent.com/23411890/71547175-9ddd0000-296a-11ea-92a8-930c3189d8a0.png)
But this is the actual 3d model of that part:
![2019-12-28_11 58 10](https://user-images.githubusercontent.com/23411890/71547178-a59ca480-296a-11ea-817d-67536eabc84b.png)
As you can see, there are two holes missing from the 3d model, as well as the ziptie slots. on the side.  These holes are where the spring guide anchor block is mounted, so now I can't attach that piece because the holes are missing.

**Comment by vcapra1** [comment]
I'm closing this issue as it appears the guide block isn't necessary, so the missing holes are not a problem.
