### ISSUE TITLE
Photos for Build Plate Assembly, Z-Axis Assembly Instructions

### ISSUE THREAD

**Issue by cindygfeng** [machineagency/jubilee#83]
Not sure if you want this photo for the Build Plate Assembly because the Heated Pad is already installed, but here it is:
![image](https://user-images.githubusercontent.com/49258117/80045343-ed1be300-84bb-11ea-8077-65a4e4582ff4.png)

Also here's a photo for the last sheet of Z-Axis Assembly:
![image](https://user-images.githubusercontent.com/49258117/80046204-cc08c180-84be-11ea-8ee6-12636aad4fa1.png)

**Comment by Poofjunior** [comment]
OMG those are AMAZING. thats perfect for the docs. Thanks!

**Comment by cindygfeng** [comment]
No problem @Poofjunior ! Here is maybe a better version of the second image (I repositioned the top of the spring)
![image](https://user-images.githubusercontent.com/49258117/80046437-74b72100-84bf-11ea-8d4a-f061680ab7ea.png)

**Comment by Poofjunior** [comment]
They are added! Thanks a bunch; these look great.
