### ISSUE TITLE
z_axis_assembly.pdf does not specify length of m5 screw in diagram

### ISSUE THREAD

**Issue by SteveJWallace** [machineagency/jubilee#85]
On sheet 6 of 16 the m5 screws and drop in t-nuts are shown but are not listed in the diagram and the length of the m5 screws are not specified.

![image](https://user-images.githubusercontent.com/5131593/80783856-1d612280-8b49-11ea-9066-b26531de4045.png)

**Comment by Poofjunior** [comment]
Thanks for the heads up. This page has been removed altogether in the latest build! (Printed parts are still in the REPO though for reference.)
