### ISSUE TITLE
Spring length(s) required missing from BOM

### ISSUE THREAD

**Issue by hexblot** [machineagency/jubilee#87]
Hello,
I am in the process of sourcing the various items in the BOM from the EU and have the following requirement for clarification: 

In the given Google Sheet BOM, tab "Frame Shopping List", row 8, for "Sping Guide 0.088-in outer-dia", there are no length dimensions listed, making the pre-cut external link (lukeslab.online) the authoritative source for the needed lengths ( 1x 600mm + 1x106.5mm).

1) Kindly confirm these are correct (and only!) lengths required
2) Kindly update the BOM to reflect these values instead of relying on an external source to provide the info.

Thank you in advance!

**Comment by Poofjunior** [comment]
Yes, these are correct! Their lengths are now listed in the BOM as well. Thanks for the catch!
