### ISSUE TITLE
Extruder Nozzle does not extend below tool plate

### ISSUE THREAD

**Issue by vcapra1** [machineagency/jubilee#9]
I think this picture pretty much sums it up:

![IMG_20200102_135329](https://user-images.githubusercontent.com/23411890/71686331-e4669c00-2d68-11ea-9a53-36437433fd24.jpg)

I know it would be pretty easy for me to design an adaptor for this, but I figured I'd put something here since these are the parts listed on the BOM

**Comment by Poofjunior** [comment]
Hmm, there are definitely missing parts in this assembly. Check the latest version of the files on the development branch:
https://github.com/machineagency/jubilee/tree/dev/jubilee_2.0/cads/tools/direct_drive_bondtech_groovemount_extruder

**Comment by Poofjunior** [comment]
The extruder now has assembly instructions. Hopefully, that clears up the order of assembly.
https://github.com/machineagency/jubilee/blob/master/tools/jubilee_tools/tools/extruders/direct_drive_bondtech_groovemount_extruder/assembly_instructions/bondtech_groovemount_extruder_assembly_instructions.pdf
