### ISSUE TITLE
Carriage Center Plate screws should have inserts.

### ISSUE THREAD

**Issue by SteveJWallace** [machineagency/jubilee#95]
I would suggest either heat set inserts should be added or have the bolts go through the carriage completely as they are very likely to strip out when tightened and make disassembly difficult. It also allows for better compression.

**Comment by Poofjunior** [comment]
Aye; this will be out in the next release. The carriage front and back plates do need to be occasionally removed for servicing, so this is a good way to prevent folks from stripping screws.

**Comment by Poofjunior** [comment]
This is done :)
