### ISSUE TITLE
Default Tool Wiring, numbers don't add up?

### ISSUE THREAD

**Issue by quadrupedal** [machineagency/jubilee#96]
The Default Tool Wiring for Duet2 (https://github.com/machineagency/jubilee/blob/master/tools/jubilee_tools/tools/extruders/direct_drive_bondtech_groovemount_extruder/assembly_instructions/wiring/duet2_bondtech_default_tool_wiring.pdf) gives a suggested sleeved length of 1650mm with  exposed lengths of 100mm and 200mm for each end, which gives a total length of 1950mm, which doesn't match the given suggested total harness length of 1800mm, so it is not clear how these numbers relate to each other.

**Comment by Poofjunior** [comment]
Thanks for the heads up. Just fixed this. It also looks like these should be about 2400mm, based on recently wiring a tool.
